controller:
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    hostName: jenkins.3.124.47.165.nip.io
  installPlugins:
  - kubernetes:1.29.4
  - workflow-aggregator:2.6
  - git:4.7.1
  - configuration-as-code:1.51
  - blueocean:1.24.6
