apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-gitops-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/vfarcic/jenkins-gitops-demo
    targetRevision: HEAD
    kustomize:
      images:
      - vfarcic/jenkins-gitops-demo:latest
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

