---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jenkins-demo
  labels:
    app: jenkins-demo
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: jenkins-demo
  targetCPUUtilizationPercentage: 80
